monitoring:
  integrity: # hashed - alert on any change
    - /etc/passwd
    - /etc/shadow
    - /etc/sudoers
    - /etc/ssh/
    - /bin/
    - /usr/bin/
  activity: # events logged but not hashed
    - tmp # just tmp for testing
    - /etc/
data:
  baseline_path: ./data/baseline.json
  log_file: logs/lynx.log
